[project]
name = "arduino-cli-interactive-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathlib>=1.0.1",
    "textual>=1.0.0",
    "textual-dev>=1.7.0",
]
